language: node_js
node_js:
  - "6"
  - "7"

before_script:
  - touch .env
  - echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> .env
  - echo "STRIPE_ALLOW_DOMAIN=$STRIPE_ALLOW_DOMAIN" >> .env

script: npm test && npm coverage

env:
  global:
  - secure: OPK1RKC9xSXUSLur3O7a+LY8/MnctQeo2+3p8TiOrA1JprO9afIfpUpNbCap2MYxCG/lekmU0vQ2QHC3d2lSNdoAsjbK+3xcms6R7NHrP7N/W2ocxMdXdr0LBkrhsjVkF/kxcu61O9L2jMGsLMpna0yUv3fc+jYD5yAmdsCT7kbUPo5nxAggCQnPWB5E4MBOn0XZBT1CWHCm0sJ5NNjPsXvqpW35gQaypYqMUOjPaJu8v69cpnHOjosfJs6VeN+Ppbcmudwt2LPjDijW1jhZPGwQW8JMgzWUfwVYyJldl3Ht+tWPVmrU6PG7fgYyHJjTwjNOcEeGxGEuvGfroYSBT9E/1k7VuReoFdZ+NGO0Dx62NXEa99ttWqQjje7avnDwgW0pXkkFuhaAHxTKoWh6wiJNOvNfV+nPLRic6kskvjJGzG/GdU9j80FyLCMZf+sUWDSHsUnHHxmMWGgzVtEuT1EJUEHvykHS67tuqD6QTDdBBok++nM79GO0b+YWip/Vu2U25wJ0io9ooqudkQT9G13D48dX37WIKTeMWjLGtzpPgvfMZYaxGbil/aqlHv6G84UoePsmqZXUXjAGmOGrl6DwPezuQhycHC2+Uj22bQO0OW3eSjWkSW+t95i/WW00c2cKWqBw2TcMMQUHPTXi2NzDJ1lwpAKXG2xKUGG23T8=
  - secure: WpocRPl8VmmWbrx7hOqV1aRGC9RdtyGOIg53u3K6Dnfi0l/SkyD4P3tnQr5wSty5/Gr9Ed/Cr7qTyNupu27q8Fif2GMu3K+6K8YIoS1qxPZPZy/4TXLvY9UWs92UcEkkrnjipZQpeFHJFilvwY+h3Nie1+8r9XEL7gw9wuyDyLa29vUckHkYPGi5JleqLsqhlsa7+GGLkNt/nBQHr2V7OAPIk+knOE/bUnWgQC4EyMOwSMT9ZI7f7ltt19xsy19iUwJGXzdwKBZejRIoSpg4HxTAODJacstmXMwjvQdc75geAwjPWCvHY8ua0T4Xd4ENDWZtpNrCv7fEHypBod7UqcPnRDhE2+N0wBIA+1Mqfd7kNK/DrAxHfT0OkpOYck/CRZyVLTo+FeJaUZquetB1gZ7N/iDMAB30TWdAfudcj9kf8k1zdyITs9yTCIt86j1U30hFOc0eQDITUijjYOWLzsVaD/lmvjI05BDr+pZYq60fHVbIG+iFtmdBcI9Ff+G3af4sog+Kb7Rq1hvDj+Ysi5jB7ljNhwa2X4LDw1uKNQF5g8fUoCbsSt2lv5RChWdGkmh9FbQQcbDDz3OTTEsHrHrPDNm+4C+ncQveuEgVK783bS7WWZ+0MG3gTkAzuUmPczC5yHepMb7Jp4Llz7snt2dMCYJOcI7O3N6WhIeL8fQ=
  - secure: cAWz7+02EFakeGmG+bENyylrskgSUvvXhs6xXTjl2+l+VxsqtSqYVKq/EGk7fGyjcCu9eN6c63UgMRlfRnBC/Z63LKI5gl4cOqwQJo/nP3y/D3VXadQN6+7UMq+XL2niESfWS33j9dDsM8btmYVqmZW9mu5wu6y8Q/WWzddkKzJFNyHG5WJx8w5nMie9bZY8LuqyvY4JQHKsGc5eyVPBRpI0f+T7TLzznnYk46CT8SZLOfCeT2hz+EXu5be2d6IyKwL2tLFesXs03dcRkA2Cp5pslfHO6PX46jvhSstH6iX894Ronch3yPl1JCtqy7Mj98vhNX5jx2KcJYIrxwx+4rkU/ZJ2U+BQtEorE/ETX7MseLVU6fYdALr0rOJCZ1bzhpz9mau+d1wqdsNy7tZp+/AuC372utPk8tRRiNecr6qs8tmgO1LhTZHMbre3+v7+4ATXroJ+kROV6uopr+Opt+4T+CVT0uBfZtyGbNbNkwIMgemG1JQQ7eVGMJVt4PmonIyBW+dW7kYay4tYc9Z0VD8nCIiuhGbKQWqMmjNc+Xcry5WyXcntDROdhpIqFuGnXvNex6PSEF2UCYRdQajx76HsPFqj5QtAmyIFhL45q+i2RzCGvBraiAuQ8dz6ym0QNm462AYHJOkBKOi9EstMizEZKXb/zzP1LyaSj1WZiug=

notifications:
  email: false
