language: node_js
node_js:
- '7'
before_script:
- touch .env
- echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> .env
- echo "STRIPE_ALLOW_DOMAIN='*'" >> .env
script:
- npm run lint
- npm test
- npm run coverage
notifications:
  email: false
env:
  global:
  - secure: dLJ4+96NoP3zd3IoFjzglKMfIvGCmXR1EYjcHuU7aoKDBwJaQ0cPlZEL+iUYcjPRPtwK5TYBJsrIfL+XxLE4uP9NBsuSEtESs4VZVUTMTHxNlU9I/EesejWrvc24FXOV5r5/5P70AcNWIwPwbQWbhMkgEg5khRL4QbL1cfhKB9BURr/JrCARk4g5bTopDrNpZLFPVAMzf9ONRhTL35B7cJKkkVfV0OQA4sF/J+a5uT04IRxDoa/wiuDIa2HMr35gNDVvaqVeJ7PXzixLa+vzK9MEL+TNPVgnYiBOzEA/ht/1F2lrhWv920dHRFtyeq1yrtqxPLVM3h0k5Z7l9CP1Yl99p9oqRT7Rvjrqrbs+HHhi+0y70JhrR76wUDTa+PNWLb6VeaNVwWRBg6qDVHxDwBoyda2u8IM+Tb9+O7jjacrAsGHhlJ/Ps0ckhEeiYphzostmk9owcjmYv6lRe09Lzr69W1DyAuBPw1U0QGIAsJ/qSW1DR3QEAG/VFMBidjSTZOd3CYpW7dID0OHjJmtm+S4+g33vWaV+66fxI/nA9uFI/h2V+kiFHbClXWtDXzcmmduZ0/B04LWdDXsj7HC1GTdeoxev3AJTi/Re+w03DiGCUPS2ojxL7Y/tP/RniNN+14AqZIBRuG7WHGYwSj1O5KJtg9wVyOrZsR4PdsrC5bY=
  - secure: d6LX9M8TJLawiZ73jylxxkFJZ3N08Bgz9eMWI4B7rxjD1vjr0JMeC66sR/DmcClWyhvkbx5GM1CQavVwt1FMWQR0F/ULjaVHm/HNM8/FBEQ2e3snDg6C9rZOBHhf/g2hVF0VZ34FPA0SQUAG4yw7kYt6PEYjV3ZRXJ4z6wUt+cNKWjXWOQ4/lW6NIwsfCsDTY+c0i0O8XKalwk5GyIQY4wFJGtr5fV34BwE7Kmmilg31uL2spgaZefSfdCceUz5FDu63cz6LLy4Nm3ac0Orn46bc99knEKrOb7X9glEJxP3+e/XwzRJMp5DMoSn5UecUk7Ei2PbctOzpmRju7Rf/FZmthRpXXilaVAupL/VboN1w+p4S4YGU6g1jcMJeNtU18Sn4o6TmOLddxzNewAr3UBETYo2H1xFNfm2zX1ED5BvbjLi6KsG8Z1Te/y86boprQ9cCjDfMDh1Bc7C+uJz14biwPIKnFZmT7xtvOjbpHozLG9G5ROoXEp8WXLANiLHE662CmjIlbdjb8eqQkTqemQKyr9w10eaCphT/zQU9rdLKoLi70Yu+0jzyD+0j+7xcrfh+5F6uk01XgJCKWK9V7gRbUo1grfXVpS494sbgwCYCY0SAq4WA0lilMfjvWKYXROV5dkzFrgctof3dsDcVod9nAgGNCo923baK1/LPhz4=
